package com.hevs.projectcloud.touristofficehealthyservice;

import android.app.Activity;
import android.content.Intent;
import android.support.v7.app.ActionBarActivity;
import android.os.Bundle;
import android.view.Menu;
import android.view.MenuItem;
import android.app.Activity;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;

import com.hevs.projectcloud.touristofficebackend.tohsaService.TohsaService;
import com.hevs.projectcloud.touristofficebackend.tohsaService.model.TextCollection;

import java.io.IOException;


public class MainActivity extends Activity {

    Button  newButton;
    Button  archivedButton;

    /**
     * The class automatically generated by the Google App Engine backend
     * project, used to access the API easily from the Android application.
     */
    private TohsaService tohsaServiceAPI;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        // Get layout objects instance
        newButton       = (Button)  findViewById(R.id.archivedButton);
        archivedButton  = (Button)  findViewById(R.id.newButton);

        //LG/ Handle to the GAE endpoints in the backend
        tohsaServiceAPI = CloudEndpointBuilderHelper.getEndpoints();

        //LG/ Get the first Text from the API and display it in a TextView
        //LG/ This is for testing reasons (accessing the backend API)
        TextView readmeTextView = (TextView) findViewById(R.id.readmeText);
        String readmeText = retrieveTexts().getItems().get(1).getTextEN();
        readmeTextView.setText(readmeText);
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    /**
     * onClick event response
     * @param view the element which was clicked
     */
    public void onClick(View view) {
        Intent intent;

        switch (view.getId()) {
            case R.id.newButton:
                intent = new Intent(this, QuestionnaireActivity.class);
                startActivity(intent);
                break;
            case R.id.archivedButton:
                intent = new Intent(this, QuestionnaireListActivity.class);
                startActivity(intent);
                break;
        }
    }

    /**
     * Retrieves questionnaires from API
     */
    final TextCollection retrieveTexts() {

        TextCollection result;

        try {
            result = tohsaServiceAPI.texts().listTextes().execute();
        } catch (IOException e) {
            String message = e.getMessage();
            if (message == null) {
                message = e.toString();
            }
            //log.severe("Exception=" + message);
            result = null;
        }
        return result;
    }
}
