package com.hevs.projectcloud.touristofficehealthyservice;

import android.content.Intent;
import android.os.Bundle;
import android.app.Activity;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.TextView;

import com.hevs.projectcloud.touristofficebackend.tohsaService.TohsaService;
import com.hevs.projectcloud.touristofficebackend.tohsaService.model.Feedback;
import com.hevs.projectcloud.touristofficebackend.tohsaService.model.FeedbackCollection;
import com.hevs.projectcloud.touristofficebackend.tohsaService.model.Possibility;

import java.io.IOException;
import java.util.ArrayList;

public class QuestionnaireDetailsActivity extends Activity {

    /**
     * The class automatically generated by the Google App Engine backend
     * project, used to access the API easily from the Android application.
     */
    private TohsaService tohsaServiceAPI;


    /**
     * The identifier of the actual displayed question or feedback question on the screen
     */
    private long question_id;

    RadioGroup possibilitiesRadioGroup;

    /**
     * The feedback and question items of the whole questionnaire
     */
    private ArrayList<Feedback> fb_qest_items;


    @Override
    protected void onCreate(Bundle savedInstanceState) {

        tohsaServiceAPI = CloudEndpointBuilderHelper.getEndpoints();

        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_questionnaire_details);
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_questionnaire_details, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }

    /**
     * //LG/ Handles the click events from elements on the activity_questionnaire_details.xml
     * @param view the element which was clicked
     */
    public void onClick(View view) {
        Intent intent;

        switch (view.getId()) {
            case R.id.button_next_question :
                persistReply();
                loadNextQuestion(this.question_id);
                break;
        }
    }

    /**
     *
     * @param question_id the id of the actually displayed question
     */
    private void loadNextQuestion(long question_id) {

        Feedback feedback = null;

        //LG/ Try to get Feedback or Question object from the API
        try {
            feedback = tohsaServiceAPI.feedbacks().getFeedback(question_id).execute();
        } catch (IOException e) {
            e.printStackTrace();
        }

        TextView questionFeedbackText = (TextView) findViewById(R.id.details_question_text);
        questionFeedbackText.setText(feedback.getDescription().getTextFR());

        //LG/ Fill the radioButtons with data
        RadioButton rb1 = (RadioButton) findViewById(R.id.radioButton);
        RadioButton rb2 = (RadioButton) findViewById(R.id.radioButton2);
        RadioButton rb3 = (RadioButton) findViewById(R.id.radioButton3);

        int index = 0;
        //RadioGroup.LayoutParams layoutParams = new RadioGroup.LayoutParams(BIND_AUTO_CREATE);

        for(Possibility p : feedback.getPossibilities()) {
            RadioButton r = new RadioButton(this);
            r.setText(p.getDescription().getTextFR());

            //possibilitiesRadioGroup.addView(r, index, layoutParams);
            index ++;
        }

        //TODO: If it is the last question of the questionnaire, open the summary activity

            // Refresh the screen
            Intent refreshIntent = new Intent(this, QuestionnaireDetailsActivity.class);
            startActivity(refreshIntent);
    }

    private void persistReply() {

        RadioGroup possibilities = (RadioGroup) findViewById(R.id.radioGroup);
        possibilities.getCheckedRadioButtonId();

    }
}
